

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const FETCH_TEST =' FETCH_TEST';
export const FETCH_TEST_LOADING = 'FETCH_TEST_LOADING';
export const FETCH_TEST_FAILED =' FETCH_TEST_FAILED';
export const SUBMIT_TEST = 'SUBMIT_TEST';